export const LEVEL_TITLES = [
  '', 
  'Explorer',
  'Adventurer', 
  'Wanderer',
  'Seeker',
  'Initiate',
  'Fighter',
  'Warrior',
  'Sentinel',
  'Ironclad',
  'Battlelord',
  'Hexblade',
  'Spellblade',
  'Soulkeeper',
  'Dreadknight',
  'Warlord',
  'Shadowlord',
  'Runeborn',
  'Voidwalker',
  'Doomforged',
  'Legendborn',
  'Ascendant',
  'Eternal',
  'Godslayer',
  'Archon',
  'The Undying',
  'Titan',
  'Celestial',
  'Eclipse',
  'Wraithborn',
  'Deathless'
]

export const LEVEL_ITEMS = [
  null,
  { name: 'Worn Boots', icon: '👟', rarity: 'common' },
  { name: 'Leather Hood', icon: '🪖', rarity: 'common' },
  { name: "Traveller's Cloak", icon: '🧥', rarity: 'common' },
  { name: 'Iron Bracers', icon: '🛡', rarity: 'common' },
  { name: 'Steel Dagger', icon: '🗡', rarity: 'common' },
  { name: 'Chain Vest', icon: '⚙', rarity: 'uncommon' },
  { name: 'War Hammer', icon: '🔨', rarity: 'uncommon' },
  { name: 'Tower Shield', icon: '🛡', rarity: 'uncommon' },
  { name: 'Plate Gauntlets', icon: '🤜', rarity: 'uncommon' },
  { name: 'Crimson Helm', icon: '⛑', rarity: 'rare' },
  { name: 'Void Cloak', icon: '🌑', rarity: 'rare' },
  { name: 'Voidblade', icon: '⚔', rarity: 'rare' },
  { name: 'Soul Lantern', icon: '🔮', rarity: 'rare' },
  { name: 'Obsidian Shield', icon: '🖤', rarity: 'rare' },
  { name: 'Crown of Ruin', icon: '👑', rarity: 'epic' },
  { name: 'Shadow Cape', icon: '🌘', rarity: 'epic' },
  { name: 'Rune Gauntlets', icon: '✨', rarity: 'epic' },
  { name: 'Void Boots', icon: '👢', rarity: 'epic' },
  { name: 'Doomplate Armour', icon: '🦾', rarity: 'epic' },
  { name: 'Legendary Sword', icon: '⚔', rarity: 'legendary' },
  { name: 'Ascendant Wings', icon: '🪽', rarity: 'legendary' },
  { name: 'Eternal Ring', icon: '💍', rarity: 'legendary' },
  { name: 'Godslayer Axe', icon: '🪓', rarity: 'legendary' },
  { name: 'Archon Crown', icon: '👑', rarity: 'legendary' },
  { name: 'Undying Armour', icon: '🔥', rarity: 'legendary' },
  { name: 'Titan Gauntlets', icon: '💪', rarity: 'legendary' },
  { name: 'Celestial Bow', icon: '🏹', rarity: 'legendary' },
  { name: 'Eclipse Blade', icon: '🌑', rarity: 'legendary' },
  { name: 'Wraithplate', icon: '👻', rarity: 'legendary' },
  { name: 'Deathless Crown', icon: '☠', rarity: 'legendary' },
]

export const MEDALS = [
  { id: 'first_blood', name: 'First Blood', desc: 'Complete your first activity', icon: '⚡', rarity: 'bronze', cat: 'special', check: (s: any) => s.totalActivities >= 1 },
  { id: 'road_warrior', name: 'Road Warrior', desc: 'Run 50km total', icon: '🏃', rarity: 'bronze', cat: 'running', check: (s: any) => s.totalRunKm >= 50, progress: (s: any) => Math.min(s.totalRunKm / 50, 1) },
  { id: 'century_club', name: 'Century Club', desc: 'Run 100km total', icon: '🏅', rarity: 'gold', cat: 'running', check: (s: any) => s.totalRunKm >= 100, progress: (s: any) => Math.min(s.totalRunKm / 100, 1) },
  { id: 'marathoner', name: 'Marathoner', desc: 'Run 200km total', icon: '🎖', rarity: 'gold', cat: 'running', check: (s: any) => s.totalRunKm >= 200, progress: (s: any) => Math.min(s.totalRunKm / 200, 1) },
  { id: 'speed_demon', name: 'Speed Demon', desc: 'Run 500km total', icon: '💨', rarity: 'gold', cat: 'running', check: (s: any) => s.totalRunKm >= 500, progress: (s: any) => Math.min(s.totalRunKm / 500, 1) },
  { id: 'iron_will', name: 'Iron Will', desc: '10 gym sessions', icon: '💪', rarity: 'silver', cat: 'gym', check: (s: any) => s.gymSessions >= 10, progress: (s: any) => Math.min(s.gymSessions / 10, 1) },
  { id: 'titan', name: 'Titan', desc: '50 gym sessions', icon: '🏋️', rarity: 'silver', cat: 'gym', check: (s: any) => s.gymSessions >= 50, progress: (s: any) => Math.min(s.gymSessions / 50, 1) },
  { id: 'ironborn', name: 'Ironborn', desc: '100 gym sessions', icon: '🦾', rarity: 'gold', cat: 'gym', check: (s: any) => s.gymSessions >= 100, progress: (s: any) => Math.min(s.gymSessions / 100, 1) },
  { id: 'wanderer', name: 'Wanderer', desc: 'Walk 50km total', icon: '🚶', rarity: 'bronze', cat: 'walking', check: (s: any) => s.totalWalkKm >= 50, progress: (s: any) => Math.min(s.totalWalkKm / 50, 1) },
  { id: 'globe_trotter', name: 'Globe Trotter', desc: 'Walk 200km total', icon: '🌍', rarity: 'silver', cat: 'walking', check: (s: any) => s.totalWalkKm >= 200, progress: (s: any) => Math.min(s.totalWalkKm / 200, 1) },
  { id: 'pilgrim', name: 'Pilgrim', desc: 'Walk 500km total', icon: '🗺', rarity: 'gold', cat: 'walking', check: (s: any) => s.totalWalkKm >= 500, progress: (s: any) => Math.min(s.totalWalkKm / 500, 1) },
  { id: 'on_fire', name: 'On Fire', desc: '7 day streak', icon: '🔥', rarity: 'bronze', cat: 'special', check: (s: any) => s.streak >= 7, progress: (s: any) => Math.min(s.streak / 7, 1) },
  { id: 'unstoppable', name: 'Unstoppable', desc: '30 day streak', icon: '💎', rarity: 'gold', cat: 'special', check: (s: any) => s.streak >= 30, progress: (s: any) => Math.min(s.streak / 30, 1) },
  { id: 'calorie_king', name: 'Calorie King', desc: 'Burn 50,000 calories', icon: '🔮', rarity: 'gold', cat: 'special', check: (s: any) => s.totalCalories >= 50000, progress: (s: any) => Math.min(s.totalCalories / 50000, 1) },
  { id: 'inferno', name: 'Inferno', desc: 'Burn 100,000 calories', icon: '🌋', rarity: 'gold', cat: 'special', check: (s: any) => s.totalCalories >= 100000, progress: (s: any) => Math.min(s.totalCalories / 100000, 1) },
  { id: 'initiate', name: 'Initiate', desc: 'Reach level 5', icon: '⭐', rarity: 'bronze', cat: 'levels', check: (s: any) => s.level >= 5, progress: (s: any) => Math.min(s.level / 5, 1) },
  { id: 'battlelord', name: 'Battlelord', desc: 'Reach level 10', icon: '⚔', rarity: 'silver', cat: 'levels', check: (s: any) => s.level >= 10, progress: (s: any) => Math.min(s.level / 10, 1) },
  { id: 'warlord', name: 'Warlord', desc: 'Reach level 15', icon: '🗡', rarity: 'silver', cat: 'levels', check: (s: any) => s.level >= 15, progress: (s: any) => Math.min(s.level / 15, 1) },
  { id: 'legendborn', name: 'Legendborn', desc: 'Reach level 20', icon: '👑', rarity: 'gold', cat: 'levels', check: (s: any) => s.level >= 20, progress: (s: any) => Math.min(s.level / 20, 1) },
  { id: 'the_undying', name: 'The Undying', desc: 'Reach level 25', icon: '🔱', rarity: 'gold', cat: 'levels', check: (s: any) => s.level >= 25, progress: (s: any) => Math.min(s.level / 25, 1) },
  { id: 'deathless', name: 'Deathless', desc: 'Reach level 30', icon: '☠', rarity: 'gold', cat: 'levels', check: (s: any) => s.level >= 30, progress: (s: any) => Math.min(s.level / 30, 1) },
  { id: 'early_bird', name: 'Early Bird', desc: 'Log 10 morning activities', icon: '🌅', rarity: 'bronze', cat: 'special', check: (s: any) => s.morningActivities >= 10, progress: (s: any) => Math.min(s.morningActivities / 10, 1) },
  { id: 'night_owl', name: 'Night Owl', desc: 'Log 10 evening activities', icon: '🌙', rarity: 'bronze', cat: 'special', check: (s: any) => s.eveningActivities >= 10, progress: (s: any) => Math.min(s.eveningActivities / 10, 1) },
  { id: 'weekend_warrior', name: 'Weekend Warrior', desc: 'Log 20 weekend activities', icon: '🎯', rarity: 'silver', cat: 'special', check: (s: any) => s.weekendActivities >= 20, progress: (s: any) => Math.min(s.weekendActivities / 20, 1) },
  { id: 'half_marathon', name: 'Half Marathon', desc: 'Run 21km in one session', icon: '🥇', rarity: 'gold', cat: 'running', check: (s: any) => s.longestRun >= 21, progress: (s: any) => Math.min(s.longestRun / 21, 1) },
  { id: 'marathon', name: 'Marathon', desc: 'Run 42km in one session', icon: '🏆', rarity: 'gold', cat: 'running', check: (s: any) => s.longestRun >= 42, progress: (s: any) => Math.min(s.longestRun / 42, 1) },
  { id: 'triple_threat', name: 'Triple Threat', desc: 'Do all 3 activity types in one week', icon: '🎪', rarity: 'silver', cat: 'special', check: (s: any) => s.tripleWeek >= 1, progress: (s: any) => Math.min(s.tripleWeek, 1) },
  { id: 'consistent', name: 'Consistent', desc: 'Log activities for 4 weeks straight', icon: '📅', rarity: 'silver', cat: 'special', check: (s: any) => s.weekStreak >= 4, progress: (s: any) => Math.min(s.weekStreak / 4, 1) },
  { id: 'centurion', name: 'Centurion', desc: 'Log 100 total activities', icon: '💯', rarity: 'gold', cat: 'special', check: (s: any) => s.totalActivities >= 100, progress: (s: any) => Math.min(s.totalActivities / 100, 1) },
  { id: 'power_hour', name: 'Power Hour', desc: 'Complete a 2 hour gym session', icon: '⏱', rarity: 'silver', cat: 'gym', check: (s: any) => s.longestGym >= 120, progress: (s: any) => Math.min(s.longestGym / 120, 1) },
]
